---
apiVersion: apps/v1
kind: Deployment
metadata: { name: pgadmin, labels: { app: pgadmin } }
spec:
  replicas: 1
  selector: { matchLabels: { app: pgadmin } }
  template:
    metadata: { labels: { app: pgadmin } }
    spec:
      containers:
      - name: app
        image: dpage/pgadmin4:latest
        envFrom: [ { secretRef: { name: pgadmin-secrets } } ]
        ports: [ { containerPort: 80 } ]
---
apiVersion: v1
kind: Service
metadata: { name: pgadmin, labels: { app: pgadmin } }
spec:
  selector: { app: pgadmin }
  ports: [ { name: http, port: 80, targetPort: 80 } ]
