apiVersion: v1
kind: Secret
metadata: { name: pg-secret }
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: pg }
spec:
  replicas: 1
  selector: { matchLabels: { app: pg } }
  template:
    metadata: { labels: { app: pg } }
    spec:
      containers:
      - name: pg
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: pg-secret, key: POSTGRES_PASSWORD } }
        ports: [{containerPort: 5432}]
---
apiVersion: v1
kind: Service
metadata: { name: pg }
spec:
  selector: { app: pg }
  ports: [{ port: 5432, targetPort: 5432 }]
