apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpanda-custom:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: REDPANDA_ADVERTISE_HOST
              value: redpanda.dev.svc.cluster.local
            - name: REDPANDA_ADVERTISE_PORT
              value: "9092"
            - name: REDPANDA_ADVERTISE_RPC_HOST
              value: redpanda.dev.svc.cluster.local
            - name: REDPANDA_ADVERTISE_RPC_PORT
              value: "33145"
            - name: REDPANDA_SMP
              value: "1"
            - name: REDPANDA_MEMORY
              value: 1G
            - name: REDPANDA_RESERVE_MEMORY
              value: 0M
          ports:
            - containerPort: 9092
              name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
