apiVersion: apps/v1
kind: Deployment
metadata: { name: redpanda }
spec:
  replicas: 1
  selector: { matchLabels: { app: redpanda } }
  template:
    metadata: { labels: { app: redpanda } }
    spec:
      containers:
      - name: redpanda
        image: redpandadata/redpanda:v23.3.14
        args: ["redpanda","start","--overprovisioned","--check=false","--smp=1","--memory=1G","--reserve-memory=0M"]
        ports: [{ containerPort: 9092, name: kafka }]
---
apiVersion: v1
kind: Service
metadata: { name: redpanda }
spec:
  selector: { app: redpanda }
  ports: [{ name: kafka, port: 9092, targetPort: 9092 }]
