apiVersion: apps/v1
kind: Deployment
metadata: { name: prom }
spec:
  replicas: 1
  selector: { matchLabels: { app: prom } }
  template:
    metadata: { labels: { app: prom } }
    spec:
      containers:
      - name: prom
        image: prom/prometheus:v2.53.0
        args: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=24h"]
        ports: [{containerPort: 9090}]
        volumeMounts: [{ name: cfg, mountPath: /etc/prometheus }]
      volumes:
      - name: cfg
        configMap:
          name: prom-cfg
---
apiVersion: v1
kind: ConfigMap
metadata: { name: prom-cfg }
data:
  prometheus.yml: |
    global: { scrape_interval: 15s }
    scrape_configs:
      - job_name: otel
        static_configs: [{ targets: ["otel-collector.dev.svc.cluster.local:8889"] }]
---
apiVersion: v1
kind: Service
metadata: { name: prom }
spec:
  selector: { app: prom }
  ports: [{ port: 9090, targetPort: 9090 }]
