apiVersion: apps/v1
kind: Deployment
metadata: { name: apicurio-registry }
spec:
  replicas: 1
  selector: { matchLabels: { app: apicurio } }
  template:
    metadata: { labels: { app: apicurio } }
    spec:
      containers:
      - name: registry
        image: quay.io/apicurio/apicurio-registry-mem:latest
        ports: [{containerPort: 8080}]
---
apiVersion: v1
kind: Service
metadata: { name: apicurio-registry }
spec:
  selector: { app: apicurio }
  ports: [{ name: http, port: 8080, targetPort: 8080 }]
